# Generated by Django 3.0 on 2021-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mango',
            name='ripe',
        ),
        migrations.AddField(
            model_name='mango',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
