# Generated by Django 3.0 on 2021-07-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210715_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mango',
            name='description',
        ),
        migrations.AddField(
            model_name='mango',
            name='ripe',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
