# Generated by Django 3.0 on 2021-07-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210716_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='like_field',
        ),
        migrations.DeleteModel(
            name='LikeAndComment',
        ),
    ]
