# Generated by Django 3.0 on 2021-07-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_resource_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='likes',
        ),
    ]
