# Generated by Django 3.0 on 2021-07-17 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='comments',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
            preserve_default=False,
        ),
    ]
