# Generated by Django 3.0 on 2021-07-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_resource_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='comments',
        ),
    ]
