# Generated by Django 3.0 on 2021-07-17 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_resource_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='owner',
        ),
        migrations.AddField(
            model_name='comment',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='api.Resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='comment',
            field=models.ManyToManyField(through='api.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
