# Generated by Django 3.0 on 2021-07-17 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210717_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='comment',
        ),
        migrations.AddField(
            model_name='resource',
            name='comments',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Comment'),
            preserve_default=False,
        ),
    ]
