# Generated by Django 3.0 on 2021-07-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210717_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='comments',
            new_name='comment',
        ),
    ]
