# Generated by Django 3.0 on 2021-07-17 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210717_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='comment',
        ),
    ]
