# Generated by Django 3.0 on 2021-07-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210717_0153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
